---
- name: Apply Proxmox config
  hosts: pve

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: lxc_mount
      lxc_mount_is_lxc: false
      lxc_mount_mounts:
        - { src: /mnt/backup/pbs-dumps, dest: /mnt/pbs-dumps }
        - { src: /mnt/backup/kopia, dest: /mnt/kopia }
      lxc_mount_lxc_id: 107

- name: Install PBS and kopia
  hosts: backup

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: ssh

    - role: pbs

    - role: lxc_mount
      lxc_mount_is_lxc: true
      lxc_mount_mounts:
        - { src: /mnt/backup/pbs-dumps, dest: /mnt/pbs-dumps }
        - { src: /mnt/backup/kopia, dest: /mnt/kopia }
      lxc_mount_lxc_id: 107
      lxc_mount_users: [backup]

    - role: kopia
      kopia_path: /mnt/kopia
      kopia_user_uid: 3500
      kopia_group_gid: 3500

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
