---
- name: Install Docker
  hosts: docker

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: ssh

    - role: docker
      dashy_enabled: false
      traefik_enabled: false
      influxdb_enabled: false
      portainer_root_domain: tbrouwer.com
      portainer_cpus: 2
      portainer_dashy:
        description: "Dashboard | Tycho Brouwer"
      portainer_authelia_user:
        user_name: tycho
        display_name: Tycho Brouwer
      portainer_grafana_admin_user: admin
      portainer_passbolt:
        description: Passbolt | Tycho Brouwer
        user_surname: brouwer
        user_name: tycho
      portainer_authelia_config_template: templates/authelia-config.yml.j2
      portainer_dashy_config_template: templates/dashy-conf.yml.j2

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"

    - name: Set timezone
      ansible.builtin.command: timedatectl set-timezone Europe/Amsterdam
      changed_when: false
