---
- name: Install Docker
  hosts: docker

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.portainer
      portainer_root_domain: tbrouwer.com        
      portainer_dashy:
        description: "Dashboard | Tycho Brouwer"
      portainer_authelia_user:
        user_name: tycho
        display_name: Tycho Brouwer
      portainer_grafana_admin_user: admin
      portainer_passbolt:
        description: Passbolt | Tycho Brouwer
        user_surname: brouwer
        user_name: tycho
      portainer_traefik_additional_volumes:
        - /root/cert-proxmox.crt:/root/cert-proxmox.crt:ro
        - /root/tbrouwer-cloudflare-origin.cert:/root/tbrouwer-cloudflare-origin.cert:ro
        - /root/tbrouwer-cloudflare-origin.key:/root/tbrouwer-cloudflare-origin.key:ro
      portainer_authelia_config_template: "{{ lookup('file', 'templates/authelia-config.yml.j2') }}"
      portainer_dashy_config_template: "{{ lookup('file', 'templates/dashy-conf.yml.j2') }}"
      portainer_traefik_dynamic_template: "{{ lookup('file', 'templates/traefik-dynamic.yml.j2') }}"

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"

    - name: Set timezone
      ansible.builtin.command: timedatectl set-timezone Europe/Amsterdam
      changed_when: false
