---
- name: Install Factorio server
  hosts: factorio

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: ssh

    - role: factorio
      factorio_save_name: factory

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
