---
- name: Install Gitea
  hosts: all

  include_vars:
    - private_vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.factorio
      factorio_save_name: factory

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/subuid
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
