---
- name: Install Gitea
  hosts: gitea

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: ssh

    - role: postgres
      postgres_db_user: gitea
      postgres_db_name: giteadb
      postgres_db_password: "{{ gitea_db_password }}"

    - role: git

    - role: gitea
      gitea_app_name: "Gitea | Tycho Brouwer"
      gitea_db_user: gitea
      gitea_db_name: giteadb

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
