---
- name: Install Jellyfin
  hosts: jellyfin

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.jellyfin

    - role: tychobrouwer.lxc_mount
      lxc_mount_is_lxc: true
      lxc_mount_mounts:
        - { src: /media/file-share, dest: /share/file-share }
        - { src: /rpool-main/media-share/Movies, dest: /share/media-share/Movies }
        - { src: /rpool-main/media-share/Series, dest: /share/media-share/Series }
        - { src: /rpool-main/media-share/Transcodes, dest: /share/media-share/Transcodes }
      lxc_mount_lxc_id: 111
      lxc_mount_users: [jellyfin]

    - role: tychobrouwer.lxc_nvidia
      lxc_nvidia_lxc_id: 111
      lxc_nvidia_is_host: false
      lxc_nvidia_version: 535.154.05

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
