---
- name: Apply Proxmox config
  hosts: pve

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: lxc_mount
      lxc_mount_is_lxc: false
      lxc_mount_mounts:
        - { src: /media/file-share, dest: /share/file-share }
        - { src: /rpool-main/media-share/Movies, dest: /share/media-share/Movies }
        - { src: /rpool-main/media-share/Series, dest: /share/media-share/Series }
        - { src: /rpool-main/media-share/Transcodes, dest: /share/media-share/Transcodes }
      lxc_mount_lxc_id: 108

    - role: lxc_nvidia
      lxc_nvidia_lxc_id: 108
      lxc_nvidia_is_host: true
      lxc_nvidia_version: "580.82.07"

- name: Install Jellyfin
  hosts: jellyfin

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: ssh

    - role: jellyfin

    - role: lxc_mount
      lxc_mount_is_lxc: true
      lxc_mount_mounts:
        - { src: /media/file-share, dest: /share/file-share }
        - { src: /rpool-main/media-share/Movies, dest: /share/media-share/Movies }
        - { src: /rpool-main/media-share/Series, dest: /share/media-share/Series }
        - { src: /rpool-main/media-share/Transcodes, dest: /share/media-share/Transcodes }
      lxc_mount_lxc_id: 108
      lxc_mount_users: [jellyfin]

    - role: lxc_nvidia
      lxc_nvidia_lxc_id: 108
      lxc_nvidia_is_host: false
      lxc_nvidia_version: "580.82.07"

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
