---
- name: Install MATLAB
  hosts:
    - matlab

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.matlab
      matlab_install_location: /opt/matlab/R2024b
      matlab_user: matlab
      matlab_input_file: templates/matlab-input.txt

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
