---
- name: Apply Proxmox config
  hosts: pve

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: tychobrouwer.lxc_mount
      lxc_mount_is_lxc: false
      lxc_mount_mounts:
        - { src: /media/file-share/TUEindhoven, dest: /home/matlab/file-share }
      lxc_mount_lxc_id: 114

- name: Install MATLAB
  hosts:
    - matlab

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.matlab
      matlab_install_location: /opt/matlab/R2024b
      matlab_user: matlab
      matlab_input_file: templates/matlab-input.txt
      matlab_release: R2024b

    - role: tychobrouwer.lxc_mount
      lxc_mount_is_lxc: true
      lxc_mount_mounts:
        - { src: /media/file-share/TUEindhoven, dest: /home/matlab/file-share }
      lxc_mount_lxc_id: 114
      lxc_mount_users: [matlab]

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
