---
- name: Install Pi-Hole
  hosts: media_manager

  vars_files:
    - vars.yml
    - private_vars.yml

  pre_tasks:
    - name: Get configs on remote
      ansible.builtin.template:
        src: templates/"{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
        owner: root
        group: root
      with_items:
        - { src: authelia-config.yaml.j2, dest: /root/authelia-config/configuration.yaml }
        - { src: dashy-conf.yaml.j2,      dest: /root/dashy-conf.yaml }
        - { src: traefik-dynamic.yaml.j2, dest: /root/traefik-dynamic.yaml }

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.nordvpn
      nordvpn_server: nl900.nordvpn.com.udp1194
      nordvpn_route_nopull: true
      nordvpn_additional_route_addresses:
        - https://networkcalc.com/api/dns/lookup/skyhook.sonarr.tv
        - https://networkcalc.com/api/dns/lookup/apt.sonarr.tv

    - role: tychobrouwer.lxc_mount
      lxc_mount_is_lxc: true
      lxc_mount_mounts:
        - { src: /rpool-main/media-share/Movies, dest: /share/media-share/Movies }
        - { src: /rpool-main/media-share/Series, dest: /share/media-share/Series }
        - { src: /rpool-main/media-share/Torrents, dest: /share/media-share/Torrents }
      lxc_mount_lxc_id: 107

    - role: tychobrouwer.arrs
      arrs_media_owner: mountuser

  tasks:
    - name: Ensure arrs users are in mountuser group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: mountuser
        append: true
      with_items: [prowlarr, radarr, sonarr]

    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/subuid
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
