---
- name: Apply Proxmox config
  hosts: pve

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: lxc_mount
      lxc_mount_is_lxc: false
      lxc_mount_mounts:
        - { src: /rpool-main/media-share/Movies, dest: /share/media-share/Movies }
        - { src: /rpool-main/media-share/Series, dest: /share/media-share/Series }
        - { src: /rpool-main/media-share/Books, dest: /share/media-share/Books }
        - { src: /rpool-main/media-share/Torrents, dest: /share/media-share/Torrents }
      lxc_mount_lxc_id: 106

- name: Install arr services
  hosts: media-manager

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: ssh

    - role: lxc_mount
      lxc_mount_is_lxc: true
      lxc_mount_mounts:
        - { src: /rpool-main/media-share/Movies, dest: /share/media-share/Movies }
        - { src: /rpool-main/media-share/Series, dest: /share/media-share/Series }
        - { src: /rpool-main/media-share/Books, dest: /share/media-share/Books }
        - { src: /rpool-main/media-share/Torrents, dest: /share/media-share/Torrents }
      lxc_mount_lxc_id: 106

    - role: arrs
      arrs_media_owner: mountuser

  tasks:
    - name: Ensure arrs users are in mountuser group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: mountuser
        append: true
      with_items: [prowlarr, radarr, sonarr, readarr, bazarr, flaresolverr]

    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
