---
- name: Install Minecraft
  hosts: minecraft

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.minecraft
      minecraft_paper_version: 1.20.6
      minecraft_paper_build: 145
      minecraft_java_package: java-21-amazon-corretto-jdk
      minecraft_level_name: world
      minecraft_properties_template: "{{ lookup('file', 'templates/server.properties.j2') }}"

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
