---
- name: Install Minecraft
  hosts: all

  include_vars:
    - private_vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.minecraft
      minecraft_spigot_version: 1.20.4
      minecraft_java_version: 17

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/subuid
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
