---
- name: Install Pi-Hole
  hosts: pi_hole

  vars_files:
    - vars.yml
    - private_vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.pihole

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
