---
- name: Install Pi-Hole
  hosts:
    - pi-hole
    - pi-hole-2

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: ssh

    - role: pihole

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
