---
- name: Install Lighttpd for portfolio
  hosts: website

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: ssh

    - role: git

    - role: lighttpd
      lighttpd_git_source: https://github.com/TychoBrouwer/personal-website-elm.git
      lighttpd_website_name: portfolio
      lighttpd_server_address: https://{{ domain }}
      lighttpd_rules:
        - |
          url.rewrite-once = (
            "^/(dist|images|api)/(.*)$" =>      "/$1/$2",
            "^/robots.txt$"             =>      "/robots.txt",
            "^/projects(.*)$"           =>      "/index.html"
          )

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
