---
- name: Install Prometheus
  hosts: prometheus

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: ssh

    - role: prometheus
      prometheus_template: templates/prometheus.yml.j2
      prometheus_retention: 365d
      prometheus_pve_exporter: true
      prometheus_pve_user: ci@pve
      prometheus_pve_password: "{{ proxmox_ci_password }}"
      prometheus_pve_exporter_port: 9221
      prometheus_pve_exporter_address: 127.0.0.1
      prometheus_mimir_template: templates/mimir.yml.j2
      prometheus_minio_template: templates/minio.yml.j2

- name: Install Prometheus Node Exporter
  hosts:
    - proxmox_accessable
    - pve

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: node_exporter
