---
- name: Configure Proxmox for services
  hosts: pve

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.git

    - role: tychobrouwer.proxmox
      proxmox_pbs_client_directories:
          - file-share.pxar:/media/file-share
          - lxc-config.pxar:/etc/pve/lxc
      proxmox_pbs_repository: backup@pbs@192.168.1.107:main
      proxmox_backup_hours: "2,8,17,22"

  tasks:
    - name: Set timezone
      ansible.builtin.command: timedatectl set-timezone Europe/Amsterdam
      changed_when: false

    - name: Add kernel cmd fixes for random crashes
      ansible.builtin.lineinfile:
        path: /etc/kernel/cmdline
        backrefs: yes
        regexp: "^root=(?!.*idle).*$"
        line: '\1 idle=nomwait processor.max_cstate=5'
