---
- name: Apply Proxmox config
  hosts: pve

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: tychobrouwer.lxc_mount
      lxc_mount_is_lxc: false
      lxc_mount_mounts:
        - { src: /media/file-share, dest: /share/file-share }
        - { src: /rpool-main/media-share, dest: /share/media-share }
        - { src: /rpool-main/media-share/Movies, dest: /share/media-share/Movies }
        - { src: /rpool-main/media-share/Series, dest: /share/media-share/Series }
        - { src: /rpool-main/media-share/Books, dest: /share/media-share/Books }
        - { src: /rpool-main/media-share/Torrents, dest: /share/media-share/Torrents }
        - { src: /rpool-main/media-share/Transcodes, dest: /share/media-share/Transcodes }
      lxc_mount_lxc_id: 103

- name: Install Samba
  hosts: samba

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.samba
      samba_username: sambauser
      samba_shares:
        - name: file_share
          comment: private file share
          path: /share/file-share
          writable: "yes"
          browsable: "yes"
          inherit_permissions: "yes"
          force_user: sambauser
          force_group: sambauser
        - name: media_share
          comment: private media share
          path: /share/media-share
          writable: "yes"
          browsable: "yes"
          inherit_permissions: "yes"
          force_user: sambauser
          force_group: sambauser

    - role: tychobrouwer.lxc_mount
      lxc_mount_is_lxc: true
      lxc_mount_mounts:
        - { src: /media/file-share, dest: /share/file-share }
        - { src: /rpool-main/media-share, dest: /share/media-share }
        - { src: /rpool-main/media-share/Movies, dest: /share/media-share/Movies }
        - { src: /rpool-main/media-share/Series, dest: /share/media-share/Series }
        - { src: /rpool-main/media-share/Books, dest: /share/media-share/Books }
        - { src: /rpool-main/media-share/Torrents, dest: /share/media-share/Torrents }
        - { src: /rpool-main/media-share/Transcodes, dest: /share/media-share/Transcodes }
      lxc_mount_lxc_id: 103
      lxc_mount_users: [sambauser]

  tasks:
    - name: Install pip
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Set pip configuration
      ansible.builtin.command: pip3 config set global.break-system-packages True
      changed_when: false

    - name: Install icloudpd python package
      ansible.builtin.pip:
        name: icloudpd
        state: present

    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
