---
- name: Install Traefik
  hosts:
    - traefik

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: tychobrouwer.ssh

    - role: tychobrouwer.traefik
      traefik_root_domain: tbrouwer.com
      traefik_dynamic_template: "templates/traefik-dynamic.yml.j2"
      traefik_static_template: "templates/traefik-static.yml.j2"

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
