---
- name: Install Wireguard
  hosts: wireguard

  vars_files:
    - vars.yml
    - private-vars.yml

  roles:
    - role: ssh

    - role: wireguard
      wireguard_host_address: 10.6.0.1/32
      wireguard_peers:
        - public_key: "{{ wireguard_laptop_public_key }}"
          allowed_ips: 10.6.0.2/32
        - public_key: "{{ wireguard_phone_public_key }}"
          allowed_ips: 10.6.0.3/32

  tasks:
    - name: Set journald log size
      ansible.builtin.lineinfile:
        path: /etc/systemd/journald.conf
        line: SystemMaxUse=512M
        regexp: ^SystemMaxUse=
        insertafter: "[Journal]"
